---
instances:
- https://rss.shab.fun/
- https://vercel.getrss2021.xyz/
- http://getrss2021.xyz:1200/
- https://rsshub.app/
- https://rsshub.rssforever.com/
- https://hub.slarker.me/
- https://rsshub.pseudoyu.com/
- https://rsshub.ktachibana.party/
- https://rsshub.woodland.cafe/
- https://rss.owo.nz/
- https://yangzhi.app/
- https://rsshub.henry.wang/
- https://rss.peachyjoy.top/
- https://rsshub.speednet.icu/
- https://hub.rss.direct/
- https://rsshub.umzzz.com/
routes:
- title: tk 微博
  path: weibo/user/6827625527
# baseUrl: https://raw.githubusercontent.com/wdssmq/proxy_rsshub/main # The Base Url Of xml folder
